@startuml "Model"
entity User
{
    + Id : int 
    + Name : string
    + Password : string
    + Email : string
    + Role : Userrole
}
enum Userrole
{
    + Admin
    + User
}
entity Profile 
{
    + Id : int 
    + Firstname : string
    + Lastname : string
    + Description : string  
    + DateOfJoin : DateTime
}

User o-- Userrole
User ||-- Profile
@enduml